### ISSUE TITLE
Lisää velvoitetarkastelu biojätteelle

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#164]
- [x] tehdään näkymä kohteista, joita velvoite koskee (jkr.v_enint_4_huoneistoa_biojatteen_erilliskeraysalue)
- [x] muodostetaan näkymä, joka sisältää molemmat velvoitealueet (jkr.v_erilliskeraysalueet)
- [x] luodaan funktio jkr.kohteet_joilla_bio_puuttuu(date) täyttymissäännölle määrittelyn rivillä 16
- [x] luodaan funktio jkr.kohteet_joilla_bio_puuttuu_ei_kompostointia(date) täyttymissäännölle määrittelyn rivillä 17
- [x] luodaan funktio jkr.kohteet_joilla_bio_0_tai_yli_4_vk(date) määrittelyn rivillä 18
- [x] luodaan funktio jkr.kohteet_joilla_bio_enint_4_vk(date) määrittelyn rivillä 19
- [x] luodaan viisi velvoitemallia (rivin 20 täyttymissäännön funktio on jo olemassa)

Huomioitava myös kimppatapaukset.

Toinen tarvittava näkymä kohteista, joita velvoite koskee (jkr.v_vah_5_huoneistoa_hyotyjatteiden_erilliskeraysalue) sisältyy seikkaan #157.

**Comment by ismogis** [comment]
Valmiina ja testattu pintapuolisesti. Odottaa PR:n https://github.com/GispoCoding/jkr-core/pull/101 mergeä, minkä jälkeen tehdään rebase.
