### ISSUE TITLE
Lisää velvoitetarkastelu kartongille

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#165]
- [x] luodaan funktio jkr.kohteet_joilla_kartonki_puuttuu(date) täyttymissäännölle määrittelyn rivillä 24
- [x] luodaan funktio jkr.kohteet_joilla_kartonki_yli_12_vk(date) täyttymissäännölle määrittelyn rivillä 25
- [x] luodaan funktio jkr.kohteet_joilla_kartonki_enintaan_12_vk(date) täyttymissäännölle määrittelyn rivillä 26
- [x] lisätään velvoitemallit jkr.velvoitemalli-tauluun

**Comment by ismogis** [comment]
Kartonkivelvoite kohdistui 5/2022 2173 kohteeseen: luokittain 1187+1+985. Näkymässä jkr.v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue on kuitenkin 2958 kohdetta.

Kimppasopimuksen jätetyypin tarkistus puuttui: korjauksen jälkeen kohteita 2175. Lopuissa kohdistumattomissa ainakin selvästi suurimmassa osassa syynä näyttäisi olevan, ettei sopimuksella ole tyhjennysväliä.

**Comment by ismogis** [comment]
Valmiina, odottaa PR:n hyväksymistä https://github.com/GispoCoding/jkr-core/pull/104, minkä jälkeen rebase ja migraation version korjaus.
