### ISSUE TITLE
Lisää puuttuvat velvoiteyhteenvedot

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#168]
Lisätään puuttuvat velvoiteyhteenvedot määrittelyn riveiltä 33-48.

- [x] lisätään näkymä jkr.v_enint_4_huoneistoa_ei_biojatteen_erilliskeraysalue
- [x] lisätään näkymä jkr.v_vah_5_huoneistoa_ei_hyotyjatteen_erilliskeraysalue
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok (id 30)
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok_kompostointi_voimassa (id 31)
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok_bio_enint_4 (id 32)
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok_bio_enint_4_muut_voimassa (id 33)
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok_bio_puuttuu (id 35)
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok_bio_enint_4_kartonki_puuttuu (id 36)
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok_bio_enint_4_metalli_puuttuu (id 37)
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok_bio_enint_4_lasi_puuttuu (id 38)
- [x] lisätään funktio jkr.kohteet_joilla_seka_ok_bio_enint_4_muovi_puuttuu (id 39)
- [x] lisätään funktio jkr.kohteet_joilla_seka_vaara_tvali_muut_voimassa (id 40)
- [x] lisätään funktio jkr.kohteet_joilla_seka_vaara_tvali_bio_voimassa (id 41)
- [x] lisätään funktio jkr.kohteet_joilla_seka_vaara_tvali_kompostointi_voimassa (id 42)
- [x] lisätään funktio jkr.kohteet_joilla_seka_vaara_tvali (id 43)
- [x] lisätään funktio jkr.kohteet_joilla_bio_vaara_tvali_seka_voimassa (id 44)
- [x] lisätään funktio jkr.kohteet_joilla_bio_vaara_tvali_muut_voimassa (id 45)
- [x] luodaan velvoitemallit

Näkymissä riittää, että kohteen yksi rakennus on alueen ulkopuolella.
