### ISSUE TITLE
Velvoitetarkastukset aikaväleille

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#190]
Velvoitetarkastukset kohdistuvat nyt yksittäiseen päivämäärään. Muokataan velvoitetarkastuksia toimimaan aikavälille (esim. kolme kvartaalia).

Tarvitaan seuraavat askeleet.

- [x] tarkistetaan, toimivatko funktiot jkr.velvoite_status ja jkr.tallenna_velvoite_status, jos niille antaa parametrina aikavälin, korjataan tarvittaessa => KORJATTAVA
- [x] muokataan funktiot jkr.velvoite_status ja jkr.tallenna_velvoite_status siten, että niille menee parametrina sisään päivämäärä, josta muodostetaan kolmen kvartaalin pituinen ajanjakso (esim. 10.4.2022 -> Q4/2021-Q2/2022)
- [x] tauluun velvoite_status tallennetaan yksittäisen päivämäärän sijaan ajanjakso, josta on muodostettava unique index samaan tapaan kuin uidx_velvoite_status_velvoite_id_pvm
- [x] tarkistetaan vähintään pistokokein, toimiiko täyttymissääntöjen funktioissa (esim. kohteet_joilla_lasi_puuttuu) päivämäärien tarkastelu oikein, jos käytetään ajanjaksoja, korjataan tarvittaessa => KORJATTAVA
- [x] tarkistetaan, toimiiko velvoitetarkasteluissa käytettävä näkymä jkr.v_velvoitteiden_kohteet, kun taulussa velvoite_status onkin ajanjakso
- [x] kohteiden halutaan kuuluvan jätelajin sisällä sekä velvoiteyhteenvedoissa vain parhaaseen luokkaan eli on lisättävä funktioihin tarkistus, kuuluuko kohde jo muihin luokkiin (esim. funktiossa kohteet_joilla_lasi_puuttuu pitää tutkia, etteivät muut lasipakkausten funktiot palauta kohdetta)
- [x] selvitetään, mitä tehdään näkymälle v_velvoite_status_current_date = > POISTETAAN TÄSSÄ VAIHEESSA
- [x] muokataan tietomalliin tehdyt muutokset
- [x] tarkistetaan velvoitteiden toiminta QGIS-projektissa

Jos viimeistä kohtaa ei toteuteta, suodatus kohteen kuulumiseksi vain yhteen luokkaan pitää tehdä raportoinnin yhteydessä.

Tästä hieman kevyempi toteutus voisi olla jättää velvoite_status-tauluun yksittäinen päivämäärä, joka olisi esim. tarkasteltavan ajanjakson loppupäivämäärä. Silloin ajanjakson pituus oletettaisiin aina kiinteäksi (esim. kolme kvartaalia).

**Comment by ismogis** [comment]
Käytännössä kaikissa velvoitteiden tarkasteluun liittyvissä funktioissa date on vaihdettava daterangeksi.

**Comment by ismogis** [comment]
Testaukseen soveltuu hyvin ainakin kohteet_joilla_vapauttava_paatos_voimassa.

Esim. dev-kannassa päivämäärällä 1.3.22 (+ voimassa, - ei voimassa):
10952 +
11426 +
11553 +
55316 +
55317 +

Vastaavasti 1.6.22:
10952 +
11426 +
11553 +
55316 -
55317 -

Määritelty testausta varten funktio jkr.kohteet_joilla_vapauttava_paatos_voimassa_range(daterange). Jos funktion body on sama kuin funktiossa jkr.kohteet_joilla_vapauttava_paatos_voimassa, kutsu "SELECT jkr.kohteet_joilla_vapauttava_paatos_voimassa_range('[2022-03-01, 2022-06-01)')" palauttaa vain tilanteen 1.6.22.

Kun operaattorin @> vaihtaa muotoon &&, funktio toiminee oikein.

Jos voimassaolotarkistuksen muuttaa seuraavasti, palautuu em. kutsulla muuten oikea tulos, mutta vp:n null-arvojen käsittely menee pieleen:

AND (vp.alkupvm, vp.loppupvm) OVERLAPS (lower($1), upper($1))

**Comment by ismogis** [comment]
QGIS-projekti tarkistettava, kun tämä seikka on valmis.
