### ISSUE TITLE
Kohteiden luonti

### ISSUE THREAD

**Issue by LKajan** [GispoCoding/jkr-lahti#22]
Luodaan rakennuksista kohteita.

- [ ] Kiinteistöllä yksi rakennus, jossa asukas ja joka on luokitukseltaan "Yhden asunnon talo"
- [ ] Yhden asunnon talot (tyhjillään tai asuttu): DVV:n tiedoissa kiinteistön rakennuksilla sama omistaja. Voi olla yksi tai monta rakennusta. Yhdessä rakennuksessa voi olla asukkaita.
- [ ] Kerros ja rivitalot: Perusmaksurekisterin aineistosta asiakasnumero. Voi olla yksi tai monta rakennusta.
- [ ] Paritalot: molemmille huoneistoille omat kohteet
- [ ] Muut rakennukset, joissa huoneistotieto eli asukas: DVV:n tiedoissa kiinteistöllä yksi rakennus ja asukas. Voi olla 1 rakennus.
- [ ] Muut asumisen rakennukset (asuntola, palvelutalo): käyttötarkoitus + omistaja + kiinteistö
- [ ] Vapaa-ajanasunnot: kaikki samat omistajat. Perusmaksurekisterin aineistosta asiakasnumero. Voi olla yksi tai monta rakennusta.
- [ ] Koulut: käyttötarkoitus + omistaja + sijaintikiinteistö
- [ ] Muut rakennukset, joissa huoneisto: sama kiinteistö, sama omistaja.

**Comment by ltalve** [comment]
@AnniinaMet @TiiaY 

Siirretty keskustelu kohteiden nimeämisestä tänne (seikasta #67), koska liittyy kohteiden luontiin. Lahdessa huomattu, että joillakin kohteilla nimeksi ei tule omistajan nimeä. Gispo tutkinut asiaa ja kohteiden nimeäminen noudattaa nykyisellään seuraavaa logiikkaa tässä järjestyksessä:

1. Jos kohteella on asukkaita, kohteen nimeksi annetaan satunnaisesti määräytyvän yksittäisen asukkaan sukunimi. Perusmaksurekisterin kohteilla ei ole asukkaita osapuolena.
2. Jos kohteen omistaja on asunto-osakeyhtiö, kohteen nimeksi annetaan asunto-osakeyhtiön nimi.
3. Jos kohteen omistaja on osakeyhtiö, kohteen nimeksi annetaan osakeyhtiön nimi.
4. Jos kohteen omistaja on muu yritys tai yhteistö, kohteen nimeksi annetaan tämän nimi.
5. Jos kohteen omistajana on luonnollinen henkilö, kohteen nimeksi annetaan henkilön sukunimi.
6. Jos kohteella ei ole asukkaita eikä omistajaa, kohteen nimeksi tulee “Tuntematon”.

Kysymys: Halutaanko kaikkien kohteiden nimeksi omistajan nimi? Jos omistajaa ei ole, tällöin "Tuntematon"?

**Comment by TiiaY** [comment]
@ltalve @Mtk112 @ismogis 

Järjestys tulisi olla

1. Jos kohteen omistaja on asunto-osakeyhtiö, kohteen nimeksi annetaan asunto-osakeyhtiön nimi.
2. Jos kohteen omistaja on osakeyhtiö, kohteen nimeksi annetaan osakeyhtiön nimi.
3. Jos kohteen omistaja on muu yritys tai yhteistö, kohteen nimeksi annetaan tämän nimi.
4. Jos kohteella on asukkaita, kohteen nimeksi annetaan satunnaisesti määräytyvän yksittäisen asukkaan sukunimi. Perusmaksurekisterin kohteilla ei ole asukkaita osapuolena.
5. Jos kohteen omistajana on luonnollinen henkilö, kohteen nimeksi annetaan henkilön sukunimi.
6. Jos kohteella ei ole asukkaita eikä omistajaa, kohteen nimeksi tulee “Tuntematon”.

**Comment by ltalve** [comment]
@TiiaY Kiitos vastauksesta, vaihdamme järjestyksen.

**Comment by ltalve** [comment]
@Mtk112 Täydennys vielä tähän Lahdesta: Jos on useampi useampi omistaja tai useampi vanhin, näistä aakkosissa ensimmäinen otetaan kohteen nimeksi.
