### ISSUE TITLE
Taajama-alueiden lisäys tietokantaan

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#37]
Taajama-alueiden lisäämiseksi toteutettava:

- [x] Tutkitaan mitä tietoja tarvitaan taajama-alueista tietokantaan.
- [x] Tehdään 1. kohdan perusteella muutokset nykyisiin tauluihin, jos tarpeellista.
- [x] Luo .bat-tiedosto joka lukee lisättävät shapefilet ogr2ogrin avulla tietokantaan. Vaihtoehtoisesti voidaan käyttää gdal-apia.

Huom. Kuntaurakka-alueita ei viedä.

**Comment by ltalve** [comment]
Huomioitavaa: tarve alueiden voimassaololle. Esim. jos taajama-alue on laajentunut, velvoitetarkistuksen yhteydessä tarpeen tietää onko kohde tarkistusajankohdan hetkellä ollut taajamassa vai ei.

**Comment by ismogis** [comment]
Taajamarajauksella on oltava alkupäivämäärä ja loppupäivämäärä. Annetaan alkupäivämäärä parametrina.

Taajama-alueiden päivittämisestä on oma seikkansa (#142).

**Comment by ismogis** [comment]
Poistetaan nykyisestä taajama-taulusta seuraavat tarpeettomat kentät:
- tilastokeskus_id
- nimi_sv
- paivitetty

Lisätään vastaavasti:
- taajama_id (smallint) - luetaan datasta (fid)
- alkupvm (date, not null) - annetaan parametrina
- loppupvm (date) - jätetään tyhjäksi
