### ISSUE TITLE
T19 Kuljetustietojen päivitys

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#57]
**Haluan viedä kiinteän jätteen kuljetustiedot neljännesvuosittain, jotta lakisääteinen jätehuollon kuljetusrekisterinpitovelvoite täyttyy ja jätehuollon seurantaa voidaan tehdä riittävän ajantasaisesti. Tietojen viemiseksi tietokantaan tulee olla työkalu tai ohjeistettu toimintamalli.**

- [x] https://github.com/GispoCoding/jkr-lahti/issues/3
  - [x] https://github.com/GispoCoding/jkr-lahti/issues/94
  - [x] https://github.com/GispoCoding/jkr-lahti/issues/95
  - [x] https://github.com/GispoCoding/jkr-lahti/issues/96
  - [x] https://github.com/GispoCoding/jkr-lahti/issues/97
  - [x] https://github.com/GispoCoding/jkr-lahti/issues/98
- [ ] ~~https://github.com/GispoCoding/jkr-lahti/issues/68~~
- [x] #13 
- [x] #20 
- [ ] ~~#30~~ (kimppatieto tulee osana kuljetustietoja)
- [ ] ~~#33~~ (kimppatieto tulee osana kuljetustietoja)
- [ ] https://github.com/GispoCoding/jkr-core/issues/32
- [x] #99 
- [x] https://github.com/GispoCoding/jkr-lahti/issues/65

**Comment by ltalve** [comment]
12.1.2024 vahvistettu: kohdentumattomia kuljetustietoja ei viedä kantaan.
