### ISSUE TITLE
T22 DVV-aineiston päivitys

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#60]
**Haluan päivittää uudet DVV-tiedot järjestelmään kerran vuodessa, jotta seurantakohteet pysyvät riittävän ajantasaisina ja jätehuollon seurantaa voidaan tehdä riittävän ajantasaisesti. Tietojen viemiseksi tietokantaan tulee olla työkalu tai ohjeistettu toimintamalli.**

Ylivedetyt seikat päätetty jättää toistaiseksi toteuttamatta.

- [x] #22 
- [x] https://github.com/GispoCoding/jkr-lahti/issues/64
- [ ] ~~https://github.com/GispoCoding/jkr-core/issues/10~~
- [x] https://github.com/GispoCoding/jkr-core/issues/24
- [ ] ~~https://github.com/GispoCoding/jkr-lahti/issues/25~~
- [ ] ~~https://github.com/GispoCoding/jkr-lahti/issues/32~~
- [x] https://github.com/GispoCoding/jkr-core/issues/31
- [x] https://github.com/GispoCoding/jkr-lahti/issues/70
- [x] https://github.com/GispoCoding/jkr-lahti/issues/71
- [x] https://github.com/GispoCoding/jkr-lahti/issues/67
- [x] #74
- [ ] ~~https://github.com/GispoCoding/jkr-lahti/issues/75~~
- [x] https://github.com/GispoCoding/jkr-core/issues/37
- [x] https://github.com/GispoCoding/jkr-core/issues/38
- [x] https://github.com/GispoCoding/jkr-core/issues/39
- [x] https://github.com/GispoCoding/jkr-core/issues/40
- [x] https://github.com/GispoCoding/jkr-core/issues/41
- [x] https://github.com/GispoCoding/jkr-lahti/issues/76

**Comment by ltalve** [comment]
Asuntojen lkm -aineisto löytyy teamsista.
