### ISSUE TITLE
T24 Manuaalinen kohteiden korjaus

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#62]
**Haluan muokata tarvittaessa itse manuaalisesti kohteita, jotta kohteissa ei ole virheitä.**

Käyttäjällä on tarve tarkastaa kohteita ja jonkinlaisen käyttöliittymän kautta. Muodostetaan uusia kohteita tai puretaan jo olemassa olevia kohteita. Kyseessä on poikkeustapausten osalta tarkempi tarkastelu ja mahdollisten virheiden korjaus. Uuden DVV-aineiston mukana tulee uusia rakennuksia, joille pitää muodostua kohteet ja niitä on mahdollisesti tarvetta tarkastaa ja korjata.

Muokkaamiseen tulee olla työkalu tai ohjeistettu toimintamalli.

- [x] ohjeistetaan, miten rakennus poistetaan kohteelta ja lisätään toiselle qgisissä
- [x] päätetään, mitä tapahtuu muokatuille kohteille, kun kohteen voimassaolo lakkaa (omistaja/muut tiedot muuttuvat)? On jo päätetty, että kun kohteen yksikin omistaja muuttuu, tilalle luodaan uusi kohde (https://github.com/GispoCoding/jkr-lahti/issues/64).
  - [ ] <s>luodaan uudet kohteet dvv-sääntöjen perusteella, jolloin muokkaukset joudutaan tekemään uudestaan käsin. </s> TAI
  - [ ] <s>tehdään aina kopio vanhoista kohteista sellaisenaan, jolloin muokkaukset säilyvät, mutta *mitkään* kohteet eivät enää muutu koskaan vaikka dvv-data muuttuu. tämä on ristiriidassa sen kanssa, että halutaan päivittää dvv-kohteita vuosittain.</s> TAI
  - [ ] <s>merkitään tietokantaan erikseen, että kohdetta on muokattu käsin, jolloin tätä kohdetta ei enää luoda/muuteta automaattisesti dvv-tuonnin yhteydessä. kaikki kohteen rakennusmuutokset pitää tehdä jatkossa käsin. muokkaamattomat kohteet päivittyvät edelleen automaattisesti vuosittain.</s>
    - [ ] <s>Jos tietokantaan merkitään erikseen, että kohde on muokattu, halutaanko tämä merkintä joskus perua? Eli onko mahdollista, että jonain vuonna halutaan, että rakennnuksille luodaan kohde luodaan automaattisesti dvv-tietojen perusteella ja muokkaukset poistetaan, VAI pysyykö kohde ikuisesti samanlaisena, ja sitä on aina korjattava käsin?</s>
    - [ ] Luodaan uusi kohde, jos vanha kohde ei voimassa. Muokatun kohteen voi kuitenkin myös merkitä pysyvästi voimassaolevaksi (loppupäivämäärä tyhjä). Tällöin rakennuksille ei koskaan luoda uusia kohteita, sillä vanha kohde on pysyvästi voimassa.
- [x] kohteiden jakaminen useammaksi onnistuu qgisissä, mutta vaatii valtavasti klikkauksia:
  1. luodaan uusi tyhjä kohde
  2. poistetaan halutut rakennukset vanhalta kohteelta
  3. lisätään uudelle kohteelle
  4. kahdennetaan halutut osapuolet
  5. poistetaan vanhalta ja lisätään uudelle kohteelle
Tästä eteenpäin EI haluta siirtää tietoja uudelle kohteelle.
<s>  6. kahdennetaan halutut sopimukset~~
~~  7. poistetaan vanhalta ja lisätään uudelle kohteelle~~
~~  8. kahdennetaan halutut kuljetukset~~
~~  9. poistetaan vanhalta ja lisätään uudelle kohteelle~~
~~  10. jne~~</s>
MAHDOLLISESTI MYÖHEMMIN:
  - [ ] tehdään ensin tietomallimuutokset https://github.com/GispoCoding/jkr-lahti/issues/68
    - [ ] lisätään myös osapuolitauluun ulkoinen asiakastieto (kaikki kuljetusdatasta tulleet asiakkaat)
    - [ ] käyttäjä poistaa rakennukset kohteelta ja lisää ne uudelle tyhjälle kohteelle
    - [ ] käyttäjä poistaa haluamansa asiakastietorivit kohteelta ja lisää ne uudelle kohteelle
    - [ ] tehdään tietokantatriggeri, joka siirtää *kaikki* ulkoiseen asiakastietoon liittyvät sopimukset ja kuljetukset toiselle kohteelle, jos ulkoinen asiakastieto siirretään toiselle kohteelle
    - [ ] dvv-osapuolet pitäisi siirtää käsin

**Comment by Rikuoja** [comment]
Tallennetaanko tietokantaan tieto siitä, kuka on muokannut kohdetta ja milloin? Käsitelläänkö manuaalisesti muokattuja kohteita eri tavalla päivityksessä kuin muita kohteita?

**Comment by Rikuoja** [comment]
Mietittävä Laurin kanssa QGIS-käyttöliittymän workflow, miten rakennuksia lisäillään ja poistellaan kohteille, miten luodaan uusia kohteita tai yhdistetään vanhoja.

**Comment by TiiaY** [comment]
### Kysymys 1.
päätetään, mitä tapahtuu muokatuille kohteille, kun kohteen voimassaolo lakkaa (omistaja/muut tiedot muuttuvat)? On jo päätetty, että kun kohteen yksikin omistaja muuttuu, tilalle luodaan uusi kohde (https://github.com/GispoCoding/jkr-lahti/issues/64).
 luodaan uudet kohteet dvv-sääntöjen perusteella, jolloin muokkaukset joudutaan tekemään uudestaan käsin TAI
 tehdään aina kopio vanhoista kohteista sellaisenaan, jolloin muokkaukset säilyvät, mutta mitkään kohteet eivät enää muutu koskaan vaikka dvv-data muuttuu. tämä on ristiriidassa sen kanssa, että halutaan päivittää dvv-kohteita vuosittain. TAI
 merkitään tietokantaan erikseen, että kohdetta on muokattu käsin, jolloin tätä kohdetta ei enää luoda/muuteta automaattisesti dvv-tuonnin yhteydessä. kaikki kohteen rakennusmuutokset pitää tehdä jatkossa käsin. muokkaamattomat kohteet päivittyvät edelleen automaattisesti vuosittain.
 Jos tietokantaan merkitään erikseen, että kohde on muokattu, halutaanko tämä merkintä joskus perua? Eli onko mahdollista, että jonain vuonna halutaan, että rakennnuksille luodaan kohde luodaan automaattisesti dvv-tietojen perusteella ja muokkaukset 
poistetaan, VAI pysyykö kohde ikuisesti samanlaisena, ja sitä on aina korjattava käsin?

**Vastaus**: Palataan myöhemmin, kaikki vaihtoehdot tuntuu ongelmallisilta.

### Kysymys 2:
kohteiden jakaminen useammaksi onnistuu qgisissä, mutta vaatii valtavasti klikkauksia:
luodaan uusi tyhjä kohde
poistetaan halutut rakennukset vanhalta kohteelta
lisätään uudelle kohteelle
kahdennetaan halutut osapuolet
poistetaan vanhalta ja lisätään uudelle kohteelle
kahdennetaan halutut sopimukset
poistetaan vanhalta ja lisätään uudelle kohteelle
kahdennetaan halutut kuljetukset
poistetaan vanhalta ja lisätään uudelle kohteelle
jne
TAI
 tehdään ensin tietomallimuutokset https://github.com/GispoCoding/jkr-lahti/issues/68
 lisätään myös osapuolitauluun ulkoinen asiakastieto (kaikki kuljetusdatasta tulleet asiakkaat)
 käyttäjä poistaa rakennukset kohteelta ja lisää ne uudelle tyhjälle kohteelle
 käyttäjä poistaa haluamansa asiakastietorivit kohteelta ja lisää ne uudelle kohteelle
 tehdään tietokantatriggeri, joka siirtää kaikki ulkoiseen asiakastietoon liittyvät sopimukset ja kuljetukset toiselle kohteelle, jos ulkoinen asiakastieto siirretään toiselle kohteelle
 dvv-osapuolet pitäisi siirtää käsin
kohteiden jakaminen useammaksi onnistuu qgisissä, mutta vaatii valtavasti klikkauksia:
luodaan uusi tyhjä kohde
poistetaan halutut rakennukset vanhalta kohteelta
lisätään uudelle kohteelle
kahdennetaan halutut osapuolet
poistetaan vanhalta ja lisätään uudelle kohteelle
kahdennetaan halutut sopimukset
poistetaan vanhalta ja lisätään uudelle kohteelle
kahdennetaan halutut kuljetukset
poistetaan vanhalta ja lisätään uudelle kohteelle
jne
TAI
 tehdään ensin tietomallimuutokset https://github.com/GispoCoding/jkr-lahti/issues/68
 lisätään myös osapuolitauluun ulkoinen asiakastieto (kaikki kuljetusdatasta tulleet asiakkaat)
 käyttäjä poistaa rakennukset kohteelta ja lisää ne uudelle tyhjälle kohteelle
 käyttäjä poistaa haluamansa asiakastietorivit kohteelta ja lisää ne uudelle kohteelle
 tehdään tietokantatriggeri, joka siirtää kaikki ulkoiseen asiakastietoon liittyvät sopimukset ja kuljetukset toiselle kohteelle, jos ulkoinen asiakastieto siirretään toiselle kohteelle
 dvv-osapuolet pitäisi siirtää käsin

**Vastaus**: On sovittu, että kuljetustiedot ja päätökset eivät siirry uudelle kohteelle. Liittyy asiaan, että kohteilla alku- ja loppupäivämäärä.

**Comment by Rikuoja** [comment]
**Kysymys 1: Vastaus: Kommentti: Luodaan uusi kohde käsinmuodostetusta, jos omistaja tai asukas vaihtunut. Muutoin päivitetään vain kohteen tiedot (rakennukssen tiedot jne,)**

Tämä tarkoittaa silloin myös sitä, että käsin muokatut kohteet saattavat lakata olemasta. Eli jos dvv-omistajissa tapahtuu muutoksia, voi olla, että käsin tehdyt muokkaukset joudutaan tekemään uudelle kohteelle/uusille kohteille uudestaan käsin.

**Comment by Rikuoja** [comment]
**Kysymys 2: Vastaus: On sovittu, että kuljetustiedot ja päätökset eivät siirry uudelle kohteelle. Liittyy asiaan, että kohteilla alku- ja loppupäivämäärä.**

Tehdään siis niin, että käsin luodun uuden kohteen alkupäivämäärä on muokkauspäivämäärä. Sitten esim. vanhalle muokatulle kohteelle tosiaan jäävät kaikki kuljetukset, jotka ovat aiemmin kohdistuneet sille, mutta uudella kohteella ei ole mitään kuljetuksia. Jos käsin vain muokataan olemassaolevaa kohdetta, silloin vanha kohde, kuljetukset jne. pysyvät voimassa, vaikka kohteesta poistetaan rakennuksia, ja joistain rakennuksista tehtäisiin uusi kohde.

Tämä tarkoittaa siis sitä, että jos kohde jaetaan kahteen käsin (esim. valtavat kohteet, jotka on kiinteistönumeron/perusmaksun perusteella yhdistetty), toiselle (ns. uudelle) kohteelle ei tule mitään asiakkaita, kuljetuksia eikä sopimuksia. Myös mahdolliset dvv-osapuolet, rakennusten vanhimmat asukkaat, omistajat jne. pitäisi etsiä vanhan kohteen omistajista ja lisätä uudelle kohteelle käsin. Jos näitä ei lisätä uudelle kohteelle käsin, seuraavassa kvartaalissa, kun kuljetustiedot tuodaan, käsin luodulle kohteelle ei välttämättä kohdistu kuljetuksia, jos asiakkaiden nimiä ei ole lisätty.

PRT:n perusteella kohdennus toki onnistuu, koska uudella kohteella on rakennuksia. Samoin asiakasnumeron perusteella, jos uudelle kohteelle lisätään asiakasnumero käsin.

**Comment by ltalve** [comment]
Kohteiden manuaalinen muokkaus QGIS-työtilassa on käyty läpi ja ohjeistettu 5/2023. Manuaalisesti voidaan:

- lisätä kohde
- poistaa kohde
- lisätä kohteelle rakennuksia
- poistaa kohteelta rakennuksia
- muokata rakennusksen omistajien tietoja
- muokata rakennuksen asukkaiden tietoja

On vielä päättämättä miten erilaiset tehdyt manuaaliset muokkaukset halutaan tarkalleen säilyttää tai päivittää dvv-päivityksen yhteydessä. Tästä keskustelua käydään ko. seikassa #64 .

Päivityksen toteutus voi tässä mennä mutkikkaaksi, jos erilaisia käsinmuokattujen kohteiden käsittelylogiikoita on paljon. Tämän vuoksi näitä ei kannata tehdä "varmuuden vuoksi", jos ei ole varmuutta, että tarve on todellinen. Olisi hyvä miettiä, **mitkä ovat tärkeimmät/todennäköisimmät tarpeet kohteiden manuaaliselle muokkaukselle**, jotta myös päivitys voidaan suunnitella parhaalla mahdollisella tavalla. Pohdittavaksi teille @AnniinaMet @TiiaY. 

Jos halutaan toteuttaa kohteille manuaalisen muokkauksen yhteyteen QGIS-lomakkeelle valinta "Ohita tämä kohde dvv-päivityksen yhteydessä", tästä tulee tehdä oma issue.

**Comment by TiiaY** [comment]
@ltalve @ismogis 

Ennen kuin olemme katsoneet kohteet, emme voi ottaa kantaa. Koodia voinee muokata myöhemmin. Tavoite on, että ei käsin käpäillä.

**Comment by ltalve** [comment]
Päätetty kokouksessa 18.9.2023: 
Kohteiden luonnin yhteydessä kohteiden loppupäivämäärät asetetaan niin, että pm-rekisterikohteille tulee annettu päivämäärä kaukana tulevaisuudessa (esim. 1.1.2100) ja muille kohteille loppupäivämäärä jää tyhjäksi. Käsin muokatessa kohteelle tulee antaa tulevaisuuden loppupäivämäärä (esim. 1.1.2100), jolloin kohde ei jatkossa päivity.
