### ISSUE TITLE
Lisää wheel-päivitystyökaluun dvv-kohteiden luonnin tuki

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-lahti#71]
- [x] Jos päivitystyökalusta puuttuu tiedostoja/skriptejä, joita tarvitaan DVV-kohteiden tuontiin, nämä skriptit lisättävä päivitystyökaluun
- [x] Työkalusta julkaistava uusi versio, joka tukee DVV-kohteiden luontia
- [x] Mietittävä, mitä kirjastoja asiakas joutuu asentamaan omalle koneelleen näiden skriptien takia. Hoidetaanko nämä kuitenkin jollain python-paketilla, joka sisältää paikkatieto- ja tietokantakirjastot (vrt. ogr2ogr, psql)?

**Comment by Rikuoja** [comment]
Mietittävä @LKajan n ja @Mtk112 n kanssa. Miten nämä asennetaan windowsille?

**Comment by TiiaY** [comment]
Mikä on kysymys jätehuollolle?

**Comment by Rikuoja** [comment]
@TiiaY Kysymystä ei ole jätehuollolle, vaan tämä vaatii meidän sisäistä työskentelyä ja kysymyksiin vastaamista, ennen kuin tämän voi toteuttaa.
