### ISSUE TITLE
Päivitä QGIS-projekti testikäyttöä varten

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#84]
QGIS-projektissa havaittuja korjaustarpeita:

- [x] Select features by value -lomakkeilla asetettava kaikki kentät oletusarvoisesti tilaan "Exclude field" (nykyisellään satunnaisia kenttiä on valittu "Equal to" -tilaan, jolloin haut epäonnistuvat)
- [x] Rakennukset-tasolla Select features by value ei toimi. Ei löydä esim. prt:llä eikä kiinteistötunnnuksella rakennusta, joka löytyy tasolta. Virhe: Field 'rakennus_id' not found
- [x] Tre-spesifit tasot, joita Lahdessa ei tarvita, voi poistaa
- [x] Kohde-lomakkeelle asetettava oletusarvo 1 kentälle "kohdetyyppi_id". Muuten uutta kohdetta luodessa kenttä on tyhjä (vaikka näyttää täytetyltä) ja uuden kohteen tallennus kaatuu, koska kenttä on pakollinen.
- [x] Lomakkeiden oletusarvojen muodostuminen epäloogisesti => tutkittava ja korjattava
